services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
      - vault-data:/vault/data
      - ./vault:/vault
    cap_add:
      - IPC_LOCK
    entrypoint: sh -c "apk add --no-cache jq && /vault/start.sh"
    healthcheck:
      test: ["CMD", "sh", "-c", "vault status && vault kv get secret/database/credentials"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  app:
    build: .
    container_name: model-api
    depends_on:
      postgres:
        condition: service_healthy
      vault:
        condition: service_healthy
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    ports:
      - "8000:8000"
    command: ["python", "src/api.py"]
    restart: on-failure

volumes:
  postgres-data:
  vault-data:
